In [1]:
import numpy as np

In [2]:
a = np.array([[10, 15]])
b = np.array([[20, 9]])
print(a)
print(b)
print()

(a + b).T

[[10 15]]
[[20  9]]



array([[30],
       [24]])

In [3]:
#Subtracting 2 vector

(a - b).T

array([[-10],
       [  6]])

In [4]:
#Scaler

a = 2
u = np.array([[30, 15]])

(a * u).T

array([[60],
       [30]])

In [7]:
#Dot product of 2 vector
#For 2-D vectors, its the equivalent to matrix multiplication

u = np.array([10, 20])
v = np.array([25, 6])

print(10 * 25 + 20 * 6)

np.dot(u,v)

370


370

In [10]:
#Matrix Addition

a = np.array([[12, 10], [4, 6], [40, 31]])
b = np.array([[2, 8], [44, 63], [50, 10]])

print(a, end=" =a\n\n")
print(b, end=" =b\n\n")

a + b

[[12 10]
 [ 4  6]
 [40 31]] =a

[[ 2  8]
 [44 63]
 [50 10]] =b



array([[14, 18],
       [48, 69],
       [90, 41]])

In [11]:
#Matrix Subtraction

a-b

array([[ 10,   2],
       [-40, -57],
       [-10,  21]])

In [12]:
#Matrix scaler multiplication

a = 4
b = np.array([[2,5], [3, 7], [8, 6],])

a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [13]:
#Matrix & vextor multiplication

a = [[5,10], [15,20]]
b = [10, 12]

np.dot(a,b)

array([170, 390])

In [14]:
#Matrix to matrix multiplication

a = [[5,10], [15,20], [25, 30]]
b = [[3,6], [9,5]]

np.dot(a, b)

array([[105,  80],
       [225, 190],
       [345, 300]])

In [20]:
#Transpose a matrix

a = [[5,10], [15,20], [25, 30]]
print(a, end=" =a\n\n")


[[5, 10], [15, 20], [25, 30]] =a



In [22]:
#Create an identity matrix

I1 = np.eye(2)
I2 = np.eye(3)

print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")


[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



In [23]:
#Inverse a matrix

a = np.array([
    [2,1,0],
    [0,1,0],
    [1,2,1],
])
print(a, end=" =a\n\n")
print(np.linalg.inv(a), end=" = |a|")

[[2 1 0]
 [0 1 0]
 [1 2 1]] =a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = |a|