In [40]:
import tensorflow.compat.v1 as tf

tf.compat.v1.disable_eager_execution()

print(tf.__version__)

2.8.2


In [41]:
#CONSTANT

con1 = tf.constant(10)
con2 = tf.constant(3.14)
con3 = tf.constant("This is spartaa")
con4 = tf.constant(False)

In [42]:
print([con1,con2,con3,con4])

[<tf.Tensor 'Const_15:0' shape=() dtype=int32>, <tf.Tensor 'Const_16:0' shape=() dtype=float32>, <tf.Tensor 'Const_17:0' shape=() dtype=string>, <tf.Tensor 'Const_18:0' shape=() dtype=bool>]


In [43]:
sess = tf.compat.v1.Session()

In [44]:
result = sess.run([con1,con2,con3,con4])

In [45]:
print(result)

[10, 3.14, b'This is spartaa', False]


In [46]:
#OPERATIONS

Addition = tf.constant(20) + tf.constant(30)
Multiplication = tf.constant(20) * tf.constant(30)

In [47]:
sess.run([Addition, Multiplication])

[50, 600]

In [48]:
Addition = tf.constant([1,2,3,4,5]) + tf.constant([5,4,3,2,1])
Multiplication = tf.constant([1,2,3,4,5]) * tf.constant([5,4,3,2,1])

In [49]:
sess.run([Addition, Multiplication])

[array([6, 6, 6, 6, 6], dtype=int32), array([5, 8, 9, 8, 5], dtype=int32)]

In [50]:
str1 = tf.constant("I love ")
str2 = tf.constant("0")

In [51]:
sess.run(str1+str2)

b'I love 0'

In [52]:
#PLACEHOLDER

a = tf.placeholder(tf.int32)
b = a*2

In [53]:
sess.run(b, feed_dict={a:[1,2,3,4,5]})

array([ 2,  4,  6,  8, 10], dtype=int32)

In [54]:
#STRING PLACEHOLDER

str_name = tf.placeholder(tf.string)
my_name ="I am " + str_name

In [55]:
sess.run(my_name, feed_dict={str_name:["Sam","Bob","Neo"]})

array([b'I am Sam', b'I am Bob', b'I am Neo'], dtype=object)

In [56]:
#VARIABLE

var1 = tf.Variable([20],tf.int32)

In [57]:
init = tf.global_variables_initializer()

In [58]:
sess.run(init)

In [59]:
sess.run(var1)

array([20], dtype=int32)

In [60]:
updated_var1 = tf.assign(var1,[25])

In [61]:
sess.run(updated_var1)

array([25], dtype=int32)

In [62]:
#LINEAR MODEL

W = tf.Variable([10],tf.int32)
b = tf.Variable([5],tf.int32)
x = tf.placeholder(tf.int32)

In [63]:
linear_model= W*x +b

In [64]:
init1 = tf.global_variables_initializer()

In [65]:
sess.run(init1)

In [66]:
sess.run(linear_model, feed_dict={x:[1,2,3,4,5]})

array([15, 25, 35, 45, 55], dtype=int32)